# Generated by Django 2.1.7 on 2019-03-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_userinfo_do_hindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='topic_selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='url_idx',
            field=models.IntegerField(default=0),
        ),
    ]
